### ISSUE TITLE
Add some tests

### ISSUE THREAD

**Issue by freddiev4** [CS411F17/project#16]
**HTML Form Tests**:
- [ ] When users enter some data into the HTML form, we want to test that our `index()` function handles invalidated data properly; with an error and some helpful message
- [ ] When users enter some data into the HTML form, we want to test that we have some handler for when Yelp has no results

**Comment by freddiev4** [comment]
x-ref #17

**Comment by Simenhug** [comment]
I'll take a look

**Comment by freddiev4** [comment]
Also just came across https://hypothesis.readthedocs.io/en/latest/

**Comment by freddiev4** [comment]
There's a spreadsheet we have to use which I shared with you all last week

**Comment by freddiev4** [comment]
I believe section 1 is done
