### ISSUE TITLE
Similarity metrics

### ISSUE THREAD

**Issue by csuksangium** [CS411F17/project#47]
-Convert categorical data to numerical
-Computer euclidean distance between users
-Cluster users together based on similarities

*Note: Should we preemptively cluster together? or cluster upon request

**Comment by freddiev4** [comment]
x-ref #57

**Comment by freddiev4** [comment]
I'm not entirely sure if this is possible or even if clustering is the right approach. I think this was better off being framed as a classification problem

Also I don't think we have enough time for this
