### ISSUE TITLE
play around with benchmarking

### ISSUE THREAD

**Issue by Simenhug** [CS411F17/project#54]
find where's bottleneck, brainstorm ways to make it faster

**Comment by freddiev4** [comment]
https://docs.python.org/3/library/profile.html

**Comment by freddiev4** [comment]
https://code.djangoproject.com/wiki/ProfilingDjango

**Comment by freddiev4** [comment]
https://github.com/jazzband/silk

**Comment by Simenhug** [comment]
to view the profile stats for a file, do:
python -m cProfile file.py
<img width="705" alt="screen shot 2017-12-03 at 5 44 39 pm" src="https://user-images.githubusercontent.com/21127685/33530740-3c145942-d852-11e7-8db1-f10f5c428059.png">
here's the parameters:
<img width="691" alt="screen shot 2017-12-03 at 5 45 05 pm" src="https://user-images.githubusercontent.com/21127685/33530747-57939ef8-d852-11e7-871f-8dd1bd4dc753.png">
the following functions took the longest time:
<img width="809" alt="screen shot 2017-12-03 at 5 45 26 pm" src="https://user-images.githubusercontent.com/21127685/33530751-65874eba-d852-11e7-8c5d-b57991c5dac1.png">
<img width="865" alt="screen shot 2017-12-03 at 5 45 34 pm" src="https://user-images.githubusercontent.com/21127685/33530752-6594010a-d852-11e7-93b3-635893789a80.png">
<img width="647" alt="screen shot 2017-12-03 at 5 46 46 pm" src="https://user-images.githubusercontent.com/21127685/33530753-65a0b120-d852-11e7-9443-7adb46558b7a.png">
<img width="624" alt="screen shot 2017-12-03 at 5 47 02 pm" src="https://user-images.githubusercontent.com/21127685/33530754-65ad6cda-d852-11e7-9f87-17a565bde42d.png">
I've also created a prof file for views.py, but I don't know how to read it:
<img width="838" alt="screen shot 2017-12-03 at 5 51 17 pm" src="https://user-images.githubusercontent.com/21127685/33530770-988b68be-d852-11e7-9f5a-a01ffab2d978.png">

**Comment by freddiev4** [comment]
@Simenhug most of those functions that take more time are just coming from Django which we can't fix

**Comment by freddiev4** [comment]
To visualize the `.prof` file you could use https://jiffyclub.github.io/snakeviz/
